version: '3'

services:

  pm1:
    image: hpdevelop/mcs_community:0.1
    hostname: ${PM1}
    container_name: ${PM1}
    volumes:
    #   - /tmp/community/data1:/var/lib/columnstore/data1
      - /tmp/community/data1:/data1
      - /tmp/community/storagemanager:/storagemanager
      - /tmp/community/mysql:/var/lib/mysql
    # command: sleep infinity
    env_file:
      - .env
    ports:
      - 3307:3306
    mem_limit: ${COLUMNSTORE_RAM}