apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcs-community
  name: mcs-community
spec:
  type: NodePort
  ports:
  - port: 3306
    name: mariadb
    targetPort: 3306
  selector:
    app: mcs-community